import { parseAbi } from "viem";

// Contract addresses live in ./config (driven by env vars). Re-exported here so
// existing imports of `ADDRESSES` from "@/lib/contracts" keep working.
export { ADDRESSES } from "./config";

// ABIs are written in viem's human-readable form and include the custom errors, so
// a failed transaction can be decoded into a readable message (see lib/errors.ts).

export const feeManagerAbi = parseAbi([
  "function feeInKii() view returns (uint256)",
  "function MAX_FEE() view returns (uint256)",
  "function treasury() view returns (address)",
  "function owner() view returns (address)",
]);

export const factoryAbi = parseAbi([
  "function createCollection((string name, string symbol, string baseURI, string infoURI, string placeholderURI, uint256 maxSupply, uint96 royaltyBps, uint256 mintPrice, uint64 mintStart, uint64 mintEnd, uint256 maxPerWallet, bytes32 whitelistRoot, uint64 whitelistStart, uint64 whitelistEnd, uint256 whitelistPrice, uint64 revealTime) p) payable returns (address collection)",
  "function totalCollections() view returns (uint256)",
  "event CollectionCreated(address indexed collection, address indexed creator, string name, string symbol, uint256 maxSupply)",
  "error ZeroSupply()",
  "error BadSchedule()",
  "error EnforcedPause()",
  "error InsufficientFee(uint256 required, uint256 sent)",
]);

export const collectionAbi = parseAbi([
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function maxSupply() view returns (uint256)",
  "function owner() view returns (address)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function contractURI() view returns (string)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function tokenOfOwnerByIndex(address owner, uint256 index) view returns (uint256)",
  "function royaltyInfo(uint256 tokenId, uint256 salePrice) view returns (address receiver, uint256 royaltyAmount)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function mintPrice() view returns (uint256)",
  "function mintStart() view returns (uint64)",
  "function mintEnd() view returns (uint64)",
  "function maxPerWallet() view returns (uint256)",
  "function mintOpen() view returns (bool)",
  "function tradingOpen() view returns (bool)",
  "function proceeds() view returns (uint256)",
  "function mintedBy(address account) view returns (uint256)",
  "function whitelistOpen() view returns (bool)",
  "function whitelistRoot() view returns (bytes32)",
  "function whitelistStart() view returns (uint64)",
  "function whitelistEnd() view returns (uint64)",
  "function whitelistPrice() view returns (uint256)",
  "function revealTime() view returns (uint64)",
  "function revealed() view returns (bool)",
  "function publicMint(uint256 quantity) payable",
  "function whitelistMint(uint256 quantity, bytes32[] proof) payable",
  "function revealNow()",
  "function reserveMint(address to, uint256 quantity)",
  "function endMint()",
  "function withdrawProceeds()",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event Minted(address indexed to, uint256 indexed tokenId)",
  "error MintNotOpen()",
  "error MintEnded()",
  "error WalletLimitReached()",
  "error InsufficientPayment()",
  "error SupplyCapReached()",
  "error BadQuantity()",
  "error TradingLocked()",
  "error NothingToWithdraw()",
  "error WhitelistNotOpen()",
  "error NotWhitelisted()",
  "error PlaceholderRequired()",
  "error AlreadyRevealed()",
  "error EnforcedPause()",
  "error OwnableUnauthorizedAccount(address account)",
]);

export const marketplaceAbi = parseAbi([
  "function list(address nft, uint256 tokenId, uint256 price) returns (uint256 listingId)",
  "function updatePrice(uint256 listingId, uint256 newPrice)",
  "function cancel(uint256 listingId)",
  "function buy(uint256 listingId) payable",
  "function makeOffer(address nft, uint256 tokenId, uint256 duration) payable returns (uint256 offerId)",
  "function cancelOffer(uint256 offerId)",
  "function sellNow(uint256 offerId, uint256 minAmount)",
  "function withdraw()",
  "function pendingWithdrawals(address account) view returns (uint256)",
  "function activeListingId(address nft, uint256 tokenId) view returns (uint256)",
  "function listings(uint256 listingId) view returns (address seller, address nft, uint256 tokenId, uint256 price, bool active)",
  "function offers(uint256 offerId) view returns (address bidder, address nft, uint256 tokenId, uint256 amount, uint64 expiresAt, bool active)",
  "function collectionVolumeKii(address nft) view returns (uint256)",
  "function protocolFeeBps() view returns (uint256)",
  "function nextListingId() view returns (uint256)",
  "event Listed(uint256 indexed listingId, address indexed nft, uint256 indexed tokenId, address seller, uint256 price)",
  "event PriceUpdated(uint256 indexed listingId, uint256 newPrice)",
  "event Cancelled(uint256 indexed listingId)",
  "event Sold(uint256 indexed listingId, address indexed buyer, uint256 price)",
  "event OfferMade(uint256 indexed offerId, address indexed nft, uint256 indexed tokenId, address bidder, uint256 amount, uint64 expiresAt)",
  "event OfferCancelled(uint256 indexed offerId)",
  "event OfferAccepted(uint256 indexed offerId, address indexed nft, uint256 indexed tokenId, address seller, address bidder, uint256 price)",
  "error NotSeller()",
  "error ListingNotActive()",
  "error InsufficientPayment()",
  "error ZeroPrice()",
  "error NotTokenOwner()",
  "error NotApproved()",
  "error MintingNotEnded()",
  "error OfferNotActive()",
  "error OfferExpired()",
  "error OfferTooLow()",
  "error NotBidder()",
  "error OwnerCannotOffer()",
  "error BadDuration()",
  "error TransferFailed()",
  "error NothingToWithdraw()",
  "error WithdrawFailed()",
  "error EnforcedPause()",
]);

export const rwaFactoryAbi = parseAbi([
  "function createAsset(string name_, string symbol_, uint256 totalUnits_, uint256 pricePerUnit_, uint256 ipoStart_, uint256 ipoDuration_, address assetTreasury_, string assetMetadataURI_) returns (address asset)",
  "function totalAssets() view returns (uint256)",
  "function owner() view returns (address)",
  "function isAdmin(address account) view returns (bool)",
  "event AssetCreated(address indexed asset, string name, string symbol, uint256 totalUnits, uint256 pricePerUnit, uint256 ipoStartTime, uint256 ipoEndTime, address assetTreasury)",
  "error NotAdmin()",
  "error BadIpoStart()",
  "error EnforcedPause()",
]);

export const rwaAssetAbi = parseAbi([
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function totalUnits() view returns (uint256)",
  "function unitsSold() view returns (uint256)",
  "function pricePerUnit() view returns (uint256)",
  "function ipoStartTime() view returns (uint256)",
  "function ipoEndTime() view returns (uint256)",
  "function ipoActive() view returns (bool)",
  "function isIpoOpen() view returns (bool)",
  "function ipoEnded() view returns (bool)",
  "function assetTreasury() view returns (address)",
  "function assetMetadataURI() view returns (string)",
  "function owner() view returns (address)",
  "function contributed(address account) view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function contribute() payable",
  "function closeIpo()",
  "function withdrawProceeds()",
  "function pendingTreasuryWithdrawal() view returns (uint256)",
  "event Contributed(address indexed buyer, uint256 kiiPaid, uint256 unitsMinted)",
  "error IpoNotActive()",
  "error IpoStillActive()",
  "error SoldOut()",
  "error ZeroValue()",
  "error TransfersLockedDuringIpo()",
  "error NothingToWithdraw()",
  "error WithdrawFailed()",
  "error EnforcedPause()",
]);

export const rwaMarketplaceAbi = parseAbi([
  "function listUnits(address asset, uint256 units, uint256 pricePerUnit) returns (uint256 orderId)",
  "function buyUnits(uint256 orderId, uint256 units) payable",
  "function cancelOrder(uint256 orderId)",
  "function withdraw()",
  "function pendingWithdrawals(address account) view returns (uint256)",
  "function orders(uint256 orderId) view returns (address seller, address asset, uint256 remainingUnits, uint256 pricePerUnit, bool active)",
  "function protocolFeeBps() view returns (uint256)",
  "event OrderPlaced(uint256 indexed orderId, address indexed asset, address indexed seller, uint256 units, uint256 pricePerUnit)",
  "event OrderFilled(uint256 indexed orderId, address indexed buyer, uint256 unitsBought, uint256 kiiPaid)",
  "event OrderCancelled(uint256 indexed orderId)",
  "error NotRwaAsset()",
  "error ZeroAmount()",
  "error OrderNotActive()",
  "error NotSeller()",
  "error InsufficientAllowanceOrBalance()",
  "error TooManyUnitsRequested()",
  "error InsufficientPayment()",
  "error NothingToWithdraw()",
  "error WithdrawFailed()",
  "error EnforcedPause()",
]);

export const rwaCurveAbi = parseAbi([
  "function pools(address asset) view returns (uint256 kiiReserve, uint256 unitReserve, uint256 totalShares)",
  "function shares(address asset, address provider) view returns (uint256)",
  "function price(address asset) view returns (uint256)",
  "function quoteBuy(address asset, uint256 kiiIn) view returns (uint256 unitsOut)",
  "function quoteSell(address asset, uint256 unitsIn) view returns (uint256 kiiOut)",
  "function addLiquidity(address asset, uint256 unitsMax, uint256 minShares) payable returns (uint256 sharesMinted)",
  "function removeLiquidity(address asset, uint256 sharesToBurn, uint256 minKii, uint256 minUnits)",
  "function buy(address asset, uint256 minUnitsOut) payable",
  "function sell(address asset, uint256 unitsIn, uint256 minKiiOut)",
  "function pendingWithdrawals(address account) view returns (uint256)",
  "function withdraw()",
  "event Trade(address indexed asset, address indexed trader, bool isBuy, uint256 kiiAmount, uint256 unitAmount, uint256 priceAfter, uint256 timestamp)",
  "event LiquidityAdded(address indexed asset, address indexed provider, uint256 kiiAmount, uint256 unitAmount, uint256 sharesMinted, uint256 priceAfter)",
  "event LiquidityRemoved(address indexed asset, address indexed provider, uint256 kiiAmount, uint256 unitAmount, uint256 sharesBurned, uint256 priceAfter)",
  "error NotRwaAsset()",
  "error IpoNotEnded()",
  "error NoMarket()",
  "error ZeroAmount()",
  "error PriceOutOfBand()",
  "error SlippageExceeded()",
  "error InsufficientShares()",
  "error TransferFailed()",
  "error NothingToWithdraw()",
  "error EnforcedPause()",
]);

export const rwaChatAbi = parseAbi([
  "function post(address asset, string text) returns (uint256 messageId)",
  "function setHidden(uint256 messageId, bool isHidden)",
  "function hidden(uint256 messageId) view returns (bool)",
  "function isModerator(address account) view returns (bool)",
  "function owner() view returns (address)",
  "event MessagePosted(address indexed asset, address indexed author, uint256 indexed messageId, string text, uint256 timestamp)",
  "error NotRwaAsset()",
  "error NotAHolder()",
  "error EmptyMessage()",
  "error MessageTooLong()",
  "error TooFast()",
  "error NotModerator()",
  "error EnforcedPause()",
]);
